### ISSUE TITLE
Can not find a command to delete a recording from the savelist

### ISSUE THREAD

**Issue by genboy** [McpeBooster/ReplaySystem-McpeBooster#3]
I tested the plugin, COOL! 
In combination with Cameraman and Festival plugin triggering replay recording start and stop and replaying automatically while taking the player into cameraman-mode presenting a ghostly flashback. REALLY AWESOME! 

But how can I delete a Replay recording from the savelist with a command? 
Sorry couldn't find it.

**Comment by McpeBooster** [comment]
Ohh i forgot it... I will add it soon!

**Comment by McpeBooster** [comment]
It is added in the latest version! https://github.com/McpeBooster/ReplaySystem-McpeBooster/releases/tag/1.2
