### ISSUE TITLE
After restart server down

### ISSUE THREAD

**Issue by genboy** [McpeBooster/ReplaySystem-McpeBooster#4]
Hi at the moment my server does not work after restart with the Replay plugin. I've tested without Replay plugin installed and that works fine. Maybe it is something with auto update, i'm not sure. 

Just to let you know i can't test the plugin right now because of this. There is no error log or anything. Only after loading and enabling all plugins the server starts disabling everything and then stops.

**Comment by McpeBooster** [comment]
Please Download the latest Version, then its work!
